QUESTION_BANK = {
    "azure": [
        {
            "id": "az-001",
            "prompt": "Que servicio de Azure se usa principalmente para ejecutar maquinas virtuales?",
            "topic": "Azure fundamentals",
            "difficulty": "basic",
            "correct_option_key": "a",
            "options": [
                {"key": "a", "label": "Azure Virtual Machines"},
                {"key": "b", "label": "Azure Monitor"},
                {"key": "c", "label": "Azure DevOps Boards"},
                {"key": "d", "label": "Azure Policy"},
            ],
        },
        {
            "id": "az-002",
            "prompt": "Si tu app necesita almacenar secretos sin ponerlos en codigo, que servicio encaja mejor?",
            "topic": "Security",
            "difficulty": "basic",
            "correct_option_key": "c",
            "options": [
                {"key": "a", "label": "Azure Load Balancer"},
                {"key": "b", "label": "Azure CDN"},
                {"key": "c", "label": "Azure Key Vault"},
                {"key": "d", "label": "Azure Bastion"},
            ],
        },
        {
            "id": "az-003",
            "prompt": "Que ventaja principal ofrece Azure App Service frente a desplegar manualmente en una VM?",
            "topic": "Application hosting",
            "difficulty": "intermediate",
            "correct_option_key": "b",
            "options": [
                {"key": "a", "label": "Evita usar HTTPS"},
                {"key": "b", "label": "Reduce tareas de administracion de infraestructura"},
                {"key": "c", "label": "Obliga a usar contenedores"},
                {"key": "d", "label": "Solo sirve para apps moviles"},
            ],
        },
        {
            "id": "az-004",
            "prompt": "Que componente suele usarse para integrar eventos entre servicios en arquitecturas desacopladas de Azure?",
            "topic": "Integration patterns",
            "difficulty": "intermediate",
            "correct_option_key": "d",
            "options": [
                {"key": "a", "label": "Azure DNS"},
                {"key": "b", "label": "Azure Front Door"},
                {"key": "c", "label": "Azure DevTest Labs"},
                {"key": "d", "label": "Azure Event Grid"},
            ],
        },
        {
            "id": "az-005",
            "prompt": "Cuando diseñas una solucion resiliente en Azure, que enfoque refleja mejor buenas practicas?",
            "topic": "Architecture",
            "difficulty": "advanced",
            "correct_option_key": "b",
            "options": [
                {"key": "a", "label": "Poner todo en una sola region para simplificar"},
                {"key": "b", "label": "Combinar redundancia, monitoreo y recuperacion ante fallos"},
                {"key": "c", "label": "Evitar automatizacion para tener mas control manual"},
                {"key": "d", "label": "Guardar logs solo cuando haya incidentes"},
            ],
        },
    ],
    "aws": [
        {
            "id": "aws-001",
            "prompt": "Que servicio de AWS representa computo virtual escalable tipo servidor?",
            "topic": "AWS fundamentals",
            "difficulty": "basic",
            "correct_option_key": "a",
            "options": [
                {"key": "a", "label": "Amazon EC2"},
                {"key": "b", "label": "Amazon Route 53"},
                {"key": "c", "label": "Amazon SNS"},
                {"key": "d", "label": "Amazon CloudFront"},
            ],
        },
        {
            "id": "aws-002",
            "prompt": "Que servicio es el ajuste mas directo para guardar objetos como archivos o backups?",
            "topic": "Storage",
            "difficulty": "basic",
            "correct_option_key": "b",
            "options": [
                {"key": "a", "label": "Amazon RDS"},
                {"key": "b", "label": "Amazon S3"},
                {"key": "c", "label": "Amazon EKS"},
                {"key": "d", "label": "AWS IAM"},
            ],
        },
        {
            "id": "aws-003",
            "prompt": "Que ventaja clave trae usar Lambda frente a mantener un servidor siempre encendido?",
            "topic": "Serverless",
            "difficulty": "intermediate",
            "correct_option_key": "c",
            "options": [
                {"key": "a", "label": "Lambda permite instalar cualquier hipervisor"},
                {"key": "b", "label": "Lambda reemplaza todas las bases de datos"},
                {"key": "c", "label": "Lambda ejecuta codigo por evento sin administrar servidores"},
                {"key": "d", "label": "Lambda solo funciona dentro de VPC privadas"},
            ],
        },
        {
            "id": "aws-004",
            "prompt": "Si varias aplicaciones necesitan enviar mensajes desacoplados con tolerancia a picos, que servicio encaja mejor?",
            "topic": "Integration patterns",
            "difficulty": "intermediate",
            "correct_option_key": "a",
            "options": [
                {"key": "a", "label": "Amazon SQS"},
                {"key": "b", "label": "AWS WAF"},
                {"key": "c", "label": "AWS Artifact"},
                {"key": "d", "label": "Amazon Inspector"},
            ],
        },
        {
            "id": "aws-005",
            "prompt": "Para mejorar resiliencia regional en AWS, que enfoque es mas solido?",
            "topic": "Architecture",
            "difficulty": "advanced",
            "correct_option_key": "d",
            "options": [
                {"key": "a", "label": "Confiar en una sola AZ porque simplifica costos"},
                {"key": "b", "label": "Desactivar monitoreo para evitar ruido"},
                {"key": "c", "label": "Poner credenciales en variables manuales dentro del codigo"},
                {"key": "d", "label": "Distribuir cargas y definir recuperacion entre zonas o regiones"},
            ],
        },
    ],
    "github": [
        {
            "id": "gh-001",
            "prompt": "Que elemento de GitHub se usa para automatizar flujos como pruebas o despliegues?",
            "topic": "Automation",
            "difficulty": "basic",
            "correct_option_key": "c",
            "options": [
                {"key": "a", "label": "GitHub Stars"},
                {"key": "b", "label": "GitHub Projects Classic"},
                {"key": "c", "label": "GitHub Actions"},
                {"key": "d", "label": "GitHub Topics"},
            ],
        },
        {
            "id": "gh-002",
            "prompt": "Que practica protege mejor la rama principal en un repositorio colaborativo?",
            "topic": "Collaboration",
            "difficulty": "basic",
            "correct_option_key": "b",
            "options": [
                {"key": "a", "label": "Permitir push directo a todos"},
                {"key": "b", "label": "Usar pull requests y reglas de branch protection"},
                {"key": "c", "label": "Eliminar el historial con frecuencia"},
                {"key": "d", "label": "Trabajar siempre en main"},
            ],
        },
        {
            "id": "gh-003",
            "prompt": "Que ventaja ofrece un workflow de CI al abrir un pull request?",
            "topic": "Quality",
            "difficulty": "intermediate",
            "correct_option_key": "a",
            "options": [
                {"key": "a", "label": "Detecta fallos temprano antes de fusionar cambios"},
                {"key": "b", "label": "Evita escribir documentacion"},
                {"key": "c", "label": "Reemplaza por completo las revisiones humanas"},
                {"key": "d", "label": "Convierte cualquier repo en privado"},
            ],
        },
        {
            "id": "gh-004",
            "prompt": "Si quieres reutilizar pasos estandarizados entre varios pipelines, que enfoque encaja mejor?",
            "topic": "Workflow design",
            "difficulty": "intermediate",
            "correct_option_key": "d",
            "options": [
                {"key": "a", "label": "Duplicar cada workflow en todos los repositorios"},
                {"key": "b", "label": "Guardar secretos en texto plano"},
                {"key": "c", "label": "Ejecutar deploys solo desde laptops locales"},
                {"key": "d", "label": "Usar acciones reutilizables o workflows reutilizables"},
            ],
        },
        {
            "id": "gh-005",
            "prompt": "Que describe mejor una buena postura de seguridad en GitHub para equipos?",
            "topic": "Security",
            "difficulty": "advanced",
            "correct_option_key": "c",
            "options": [
                {"key": "a", "label": "Compartir tokens entre todo el equipo"},
                {"key": "b", "label": "Desactivar revisiones para acelerar merges"},
                {"key": "c", "label": "Aplicar minimo privilegio, secretos seguros y escaneos automaticos"},
                {"key": "d", "label": "Subir llaves privadas si el repo es temporal"},
            ],
        },
    ],
}


CERTIFICATION_TRACK_HINTS = {
    "AZ-900": "azure",
    "AZ-204": "azure",
    "AZ-400": "azure",
    "DP-900": "azure",
    "AWS Cloud Practitioner": "aws",
    "GitHub Foundations": "github",
}
